-- `body` is TipTap document JSON (jsonb), not raw HTML — per the spec's own
-- "ne pas stocker uniquement du HTML si cela empêche l'édition future"
-- (Leads Workspace spec, section 17). `body_html` is a rendered cache,
-- regenerated by the app whenever `body` is saved, used directly at send
-- time so sendEmail() never has to walk TipTap JSON itself.
create table email_templates (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  category text not null,
  subject text not null,
  body jsonb not null,
  body_html text not null,
  description text,
  variables text[] not null default '{}',
  is_active boolean not null default true,
  created_by uuid references profiles (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on table email_templates is
  'Editable from /admin/settings/email-templates. variables is informational (which {{...}} placeholders the template references), not enforced.';

create index email_templates_category_idx on email_templates (category);

alter table email_templates enable row level security;
-- Admin-only, no select policy/grant — same convention as project_tasks.

-- Seven starter templates (Leads Workspace spec, section 29) — professional,
-- short, non-pushy tone as specified. Editable from the UI once built;
-- this seed only guarantees the workspace isn't empty on day one.
insert into email_templates (name, category, subject, body, body_html, description, variables) values
(
  '01 — Premier contact', 'premier_contact', 'Votre projet avec KOV',
  jsonb_build_object('type', 'doc', 'content', jsonb_build_array(
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Bonjour {{title}} {{last_name}},'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Merci pour votre intérêt concernant {{project_name}}.'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Je serais ravi d''échanger avec vous afin de comprendre plus précisément votre projet et voir comment KOV peut vous accompagner.'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Quand seriez-vous disponible pour un premier échange ?'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Bien à vous,'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', '{{owner_name}}'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'KOV Studio')))
  )),
  '<p>Bonjour {{title}} {{last_name}},</p><p>Merci pour votre intérêt concernant {{project_name}}.</p><p>Je serais ravi d''échanger avec vous afin de comprendre plus précisément votre projet et voir comment KOV peut vous accompagner.</p><p>Quand seriez-vous disponible pour un premier échange ?</p><p>Bien à vous,</p><p>{{owner_name}}</p><p>KOV Studio</p>',
  'Premier message envoyé à un nouveau lead.',
  array['title', 'last_name', 'project_name', 'owner_name']
),
(
  '02 — Relance', 'relance', 'Suite à notre échange',
  jsonb_build_object('type', 'doc', 'content', jsonb_build_array(
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Bonjour {{title}} {{last_name}},'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Je reviens vers vous suite à notre échange concernant {{project_name}}.'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'N''hésitez pas si vous avez des questions ou si vous souhaitez qu''on approfondisse certains points.'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Bien à vous,'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', '{{owner_name}}'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'KOV Studio')))
  )),
  '<p>Bonjour {{title}} {{last_name}},</p><p>Je reviens vers vous suite à notre échange concernant {{project_name}}.</p><p>N''hésitez pas si vous avez des questions ou si vous souhaitez qu''on approfondisse certains points.</p><p>Bien à vous,</p><p>{{owner_name}}</p><p>KOV Studio</p>',
  'Relance douce après un premier contact resté sans suite.',
  array['title', 'last_name', 'project_name', 'owner_name']
),
(
  '03 — Après rendez-vous', 'apres_rdv', 'Suite à notre échange — {{company}}',
  jsonb_build_object('type', 'doc', 'content', jsonb_build_array(
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Bonjour {{title}} {{last_name}},'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Merci pour le temps accordé lors de notre échange concernant {{project_name}}.'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Je vous prépare une proposition adaptée à vos besoins et reviens vers vous très prochainement.'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Bien à vous,'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', '{{owner_name}}'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'KOV Studio')))
  )),
  '<p>Bonjour {{title}} {{last_name}},</p><p>Merci pour le temps accordé lors de notre échange concernant {{project_name}}.</p><p>Je vous prépare une proposition adaptée à vos besoins et reviens vers vous très prochainement.</p><p>Bien à vous,</p><p>{{owner_name}}</p><p>KOV Studio</p>',
  'Suivi immédiat après un appel ou un rendez-vous.',
  array['title', 'last_name', 'company', 'project_name', 'owner_name']
),
(
  '04 — Proposition', 'proposition', 'Votre proposition KOV',
  jsonb_build_object('type', 'doc', 'content', jsonb_build_array(
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Bonjour {{title}} {{last_name}},'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Vous trouverez ci-joint la proposition pour {{project_name}}.'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Je reste à votre disposition pour en discuter et l''ajuster si besoin.'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Bien à vous,'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', '{{owner_name}}'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'KOV Studio')))
  )),
  '<p>Bonjour {{title}} {{last_name}},</p><p>Vous trouverez ci-joint la proposition pour {{project_name}}.</p><p>Je reste à votre disposition pour en discuter et l''ajuster si besoin.</p><p>Bien à vous,</p><p>{{owner_name}}</p><p>KOV Studio</p>',
  'Envoi d''une proposition commerciale chiffrée.',
  array['title', 'last_name', 'project_name', 'owner_name']
),
(
  '05 — Relance proposition', 'relance_proposition', 'Votre projet — quelques nouvelles',
  jsonb_build_object('type', 'doc', 'content', jsonb_build_array(
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Bonjour {{title}} {{last_name}},'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Je me permets de revenir vers vous concernant la proposition envoyée pour {{project_name}}.'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Avez-vous eu l''occasion de la consulter ? Je suis disponible pour en discuter si vous avez des questions.'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Bien à vous,'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', '{{owner_name}}'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'KOV Studio')))
  )),
  '<p>Bonjour {{title}} {{last_name}},</p><p>Je me permets de revenir vers vous concernant la proposition envoyée pour {{project_name}}.</p><p>Avez-vous eu l''occasion de la consulter ? Je suis disponible pour en discuter si vous avez des questions.</p><p>Bien à vous,</p><p>{{owner_name}}</p><p>KOV Studio</p>',
  'Relance après l''envoi d''une proposition restée sans réponse.',
  array['title', 'last_name', 'project_name', 'owner_name']
),
(
  '06 — Prise de rendez-vous', 'prise_rdv', 'Échangeons sur votre projet',
  jsonb_build_object('type', 'doc', 'content', jsonb_build_array(
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Bonjour {{title}} {{last_name}},'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Je vous propose un échange pour discuter de {{project_name}} plus en détail.'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Quel créneau vous conviendrait le mieux cette semaine ?'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Bien à vous,'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', '{{owner_name}}'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'KOV Studio')))
  )),
  '<p>Bonjour {{title}} {{last_name}},</p><p>Je vous propose un échange pour discuter de {{project_name}} plus en détail.</p><p>Quel créneau vous conviendrait le mieux cette semaine ?</p><p>Bien à vous,</p><p>{{owner_name}}</p><p>KOV Studio</p>',
  'Invitation à caler un appel ou un rendez-vous.',
  array['title', 'last_name', 'project_name', 'owner_name']
),
(
  '07 — Dernière relance', 'derniere_relance', 'Votre projet avec KOV',
  jsonb_build_object('type', 'doc', 'content', jsonb_build_array(
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Bonjour {{title}} {{last_name}},'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Je n''ai pas eu de retour de votre part concernant {{project_name}} — je me permets donc un dernier message.'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Si le projet n''est plus d''actualité, pas de souci, n''hésitez pas à me le faire savoir. Sinon, je reste disponible quand vous le souhaitez.'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'Bien à vous,'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', '{{owner_name}}'))),
    jsonb_build_object('type', 'paragraph', 'content', jsonb_build_array(jsonb_build_object('type', 'text', 'text', 'KOV Studio')))
  )),
  '<p>Bonjour {{title}} {{last_name}},</p><p>Je n''ai pas eu de retour de votre part concernant {{project_name}} — je me permets donc un dernier message.</p><p>Si le projet n''est plus d''actualité, pas de souci, n''hésitez pas à me le faire savoir. Sinon, je reste disponible quand vous le souhaitez.</p><p>Bien à vous,</p><p>{{owner_name}}</p><p>KOV Studio</p>',
  'Dernière tentative avant de considérer le lead comme en sommeil.',
  array['title', 'last_name', 'project_name', 'owner_name']
);
